### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by marado** [eileenmcnaughton/nz.co.fuzion.civitoken#1]
Please create an INSTALL.md or something of that kind, explaining the installation process.
Thank you

**Comment by eileenmcnaughton** [comment]
I think you can just stick it in your civicrm extensions directory & then go to manage extensions, press 'refresh' so it sees it & then choose install. There are a couple of annoying enotices I haven't fixed though so if you have enotice turned on you might hit those
