### ISSUE TITLE
Compatibility with 4.7.7?

### ISSUE THREAD

**Issue by katekleiman** [eileenmcnaughton/nz.co.fuzion.civitoken#11]
I'm not able to install on Joomla 3.5.1 site with civi 4.7.7. Any updates or suggestions coming?

**Comment by eileenmcnaughton** [comment]
I'm afraid you need to download the zip file & upload it to your extensions directory - this extension does not have automatic install set up

**Comment by katekleiman** [comment]
I have tried that with no success. That procedure worked in 4.6 but not now. Thanks for the response -- I will try againKate

Get Outlook for iOS

On Wed, May 18, 2016 at 3:34 PM -0700, "Eileen McNaughton" notifications@github.com wrote:

I'm afraid you need to download the zip file & upload it to your extensions directory - this extension does not have automatic install set up

**Comment by eileenmcnaughton** [comment]
closing this as it is not related to the extension but in some way relates to extensions in a prior 4.7 version
