### ISSUE TITLE
Proposal: exclude test memberships from latestcurrentmembership

### ISSUE THREAD

**Issue by johntwyman** [eileenmcnaughton/nz.co.fuzion.civitoken#13]
I've noticed that the latestcurrentmembership tokens will include test memberships. That is to say, `is_test = 1`.

I'd argue it makes sense to change the default to exclude test memberships and perhaps make it optional to include test memberships if desired.

How does this sit with you Eileen?

Cheers,
John

**Comment by eileenmcnaughton** [comment]
I agree - it's hard to see why we need to accommodate test memberships in the token - feels like an oversight rather than a design choice

**Comment by johntwyman** [comment]
Hi @eileenmcnaughton, I've raised PR #14 to reflect this for `latestcurrentmembership` and `latestcontribs`.

**Comment by eileenmcnaughton** [comment]
great
