### ISSUE TITLE
Tokens for next pending contribution

### ISSUE THREAD

**Issue by jaapjansma** [eileenmcnaughton/nz.co.fuzion.civitoken#15]
- Amount of next contribution
- Date of next contribution

**Comment by magnolia61** [comment]
Hi Jaap, not sure if you also work with partial payments but a token for the outstanding pending balance amount would be really really nice ;-) 
I mean: contribution is 50 euro. already paid so far is 30 euro. balance is 20 euro.
A token that would show that 20 euro would be awesome. Any idea that would be easy/hard/impossible?

**Comment by jaapjansma** [comment]
That would be realy nice. I am first working on the tokens mentioned. Do you know where in the database the payments are stored? If that is easy I can add your request easily.

**Comment by eileenmcnaughton** [comment]
ping @monishdeb for advice on the best way to get that (hopefully Order api?)

**Comment by jaapjansma** [comment]
I have submitted a PR #18 which solves this issues but not the outstanding balance. I would solve that one as soon as I know how to get the payment data from the database. Could we do that in a seperate issue #19 ?

**Comment by monishdeb** [comment]
There is BAO fn to fetch the balance due amount on basis of contribution ID and its total amount : 
```php
$balanceDue = CRM_Core_BAO_FinancialTrxn::getPartialPaymentWithType(
  $row['contribution_id'],
  'contribution',
  FALSE,
  $row['total_amount']
);
```
Is that what you want?

**Comment by jaapjansma** [comment]
Thanks @monishdeb. I will add the token for @magnolia61 based on that function

**Comment by eileenmcnaughton** [comment]
@monishdeb we really should expose that via api - since it could change :-( & people would want a supported method.

@jaapjansma I think if we add a call to that function into this extension we should insist on a test as it feels high risk.  

Alternatively, @monishdeb it could be a return option on Order.get?

**Comment by eileenmcnaughton** [comment]
@jaapjansma @monishdeb @magnolia61 by the way - this extension has now been submitted to be added to extensions download - might be an easy review if you are already using it

**Comment by eileenmcnaughton** [comment]
Just checked & this is not something @jaapjansma is progressing - closing unless some momentum emerges
