### ISSUE TITLE
civitoken_civicrm_tokens removes tokens from other extensions

### ISSUE THREAD

**Issue by kainuk** [eileenmcnaughton/nz.co.fuzion.civitoken#22]
In `civitoken.php` the lines

          if (!in_array($key, $setting['civitoken_enabled_tokens'])) {
             unset($tokens[$category][$key]);
          }

are a bit too rigorous. It also removes tokens from other extensions.

**Comment by eileenmcnaughton** [comment]
ouch - open to a patch on that

**Comment by mecachisenros** [comment]
This seems like it's fixed.

**Comment by eileenmcnaughton** [comment]
oh yes -but not in a released version - I'll drop a release

**Comment by eileenmcnaughton** [comment]
Pretty sure this was resolved - closing
