### ISSUE TITLE
address block token prints "<br />"

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/nz.co.fuzion.civitoken#27]
It seems that [this line](https://github.com/eileenmcnaughton/nz.co.fuzion.civitoken/blob/master/tokens/address.inc#L38) is intentionally calling `nl2br()`, but that causes the HTML tag to be added to the mailing label:
![selection_522](https://user-images.githubusercontent.com/1796012/42531396-dd19756a-8451-11e8-9bad-94e399ddc143.png)

I'd submit a patch, but this is so obvious that maybe I'm missing something - maybe this isn't for mailing labels but for address display on the summary screen?

Also - I've got an extension that adds a UI for adding address formats to countries, which is responsive to your note about such a UI not existing.  It's still in testing, but I think it'll be ready to share very soon.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon so there are 2 address tokens - one is text & one is html - I assume you are using the html one?

**Comment by MegaphoneJon** [comment]
ummm...no, who would do that?  oops.

**Comment by eileenmcnaughton** [comment]
:-)
