### ISSUE TITLE
Fails on PHP 5.3.10 due to short array syntax

### ISSUE THREAD

**Issue by kayakr** [eileenmcnaughton/nz.co.fuzion.civitoken#30]
Error: syntax error, unexpected '[' in /home/rivers/d7_dev.rivers.org.nz/docroot/sites/all/modules/civicrm/custom_extensions/nz.co.fuzion.civitoken/civitoken.php, line 127
is using PHP short array syntax, needs a higher version of PHP

**Comment by eileenmcnaughton** [comment]
CiviCRM doesn't support php 5.3 anymore
