### ISSUE TITLE
Install fails with WSOD

### ISSUE THREAD

**Issue by TomCrawshaw** [eileenmcnaughton/nz.co.fuzion.civitoken#51]
Running Civi 5.24.2 under Drupal 7.69, PHP 7.2.29, Angular Profiles 4.7.31-1.1.2. Trying to install in usual way fails with a blank white screen, and no entries in logs to help. Also running com.pogstone.fancytokens in case that's relevant. Any ideas for diagnosis would be much appreciated.

Thanks, Tom

**Comment by eileenmcnaughton** [comment]
Are you able to edit the display_errors setting in php - perhaps you can add an override in the civicrm_settings.php file?

**Comment by TomCrawshaw** [comment]
Thanks, Eileen. That has really helped. It now shows the error:

Fatal error: Cannot redeclare civitoken_civicrm_tokens() (previously declared in /var/www/vhosts/weyarun.org.uk/httpdocs/drupal_demo/sites/all/modules/civitoken/civitoken/civitoken.module:5) in /var/www/vhosts/weyarun.org.uk/httpdocs/drupal_demo/sites/default/files/civicrm/ext/nz.co.fuzion.civitoken/civitoken.php on line 157

**Comment by TomCrawshaw** [comment]
I appear to have installed your old Drupal module 'civitoken', which was conflicting with the new Civi extension. Disabling the module now allows the installation of the extension. Thanks for the pointer to error reporting. Stay safe.
