### ISSUE TITLE
upcoming events has hardcoded types and returns if no participants.

### ISSUE THREAD

**Issue by shawnholt** [eileenmcnaughton/nz.co.fuzion.civitoken#6]
so much for my PR .  looks like the upcoming events is tied to a specific type here. and fails silently.  I think the whole token "upcomingevents" should be excluded (commented?) or repaired as it also requires that there be participants (if i read the code correctly.)  I'm sure i would mess it up.    This is much better: https://github.com/sgladstone/com.pogstone.fancytokens .

**Comment by eileenmcnaughton** [comment]
I think this is out of date now - filter has changed since then
