### ISSUE TITLE
decease date token

### ISSUE THREAD

**Issue by destrieux** [eileenmcnaughton/nz.co.fuzion.civitoken#63]
Hi I'm using CiviCRM to rule a body donation program, and I need to include the deceased_date from civicrm_contact table value as a token; is there a way to do this ? 
best

**Comment by eileenmcnaughton** [comment]
If you are on a recent version then this patch https://github.com/civicrm/civicrm-core/pull/26234 + some heavy duty cache clearing should be enough to add it to core (although I expect some tests will want fixing before I can merge that)

**Comment by destrieux** [comment]
Many thanks
I’m not familiar with patching civicdm ; where should I put this file ? 
Best

**Comment by destrieux** [comment]
Hi again 
I finally just edited wp-content/plugins/civicrm/civicrm/CRM/Contact/Tokens.php 
	to add 'deceased_date’, 
	under   protected function getExposedFields(): array {…

clean the cash 

and it works ; many thanks

**Comment by eileenmcnaughton** [comment]
Cool - I'll close this - I think the current master will be in release 5.63 so once you upgrade to that you can drop your code-hack

**Comment by destrieux** [comment]
👍Envoyé de mon iPhoneLe 17 mai 2023 à 01:22, Eileen McNaughton ***@***.***> a écrit :﻿
Cool - I'll close this - I think the current master will be in release 5.63 so once you upgrade to that you can drop your code-hack
